# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: linux_amd64
    steps:
      - name: clone code
        run: |
          git clone http://192.168.124.86:3000/learn/learn-action.git
          cd learn-action

      - name: Build
        run: go build -v ./main.go

      - name: Test
        run: go test -v ./main.go
